"""Strata Core: Pure domain models, settings, and abstract Protocols."""

from .config import Settings, get_settings
from .exceptions import (
    ChunkNotFoundError,
    DocumentNotFoundError,
    ModelInferenceError,
    SectionNotFoundError,
    StrataError,
    SyncConflictError,
)
from .models import (
    AskResult,
    BenchmarkSample,
    BenchmarkScorecard,
    Chunk,
    ChunkDiff,
    Citation,
    Document,
    DocumentOutline,
    DocumentOutlineItem,
    ExpandedContext,
    RetrievedChunk,
    RetrievedContext,
    SearchResult,
    Section,
    SyncStats,
)
from .protocols import (
    Chunker,
    DocumentStore,
    Embedder,
    HybridSearcher,
    LLMGenerator,
    Reranker,
    SparseIndex,
    VectorStore,
)

__all__ = [
    "AskResult",
    "BenchmarkSample",
    "BenchmarkScorecard",
    "Chunk",
    "ChunkDiff",
    "ChunkNotFoundError",
    "Chunker",
    "Citation",
    "Document",
    "DocumentNotFoundError",
    "DocumentOutline",
    "DocumentOutlineItem",
    "DocumentStore",
    "Embedder",
    "ExpandedContext",
    "HybridSearcher",
    "LLMGenerator",
    "ModelInferenceError",
    "Reranker",
    "RetrievedChunk",
    "RetrievedContext",
    "SearchResult",
    "Section",
    "SectionNotFoundError",
    "Settings",
    "SparseIndex",
    "StrataError",
    "SyncConflictError",
    "SyncStats",
    "VectorStore",
    "get_settings",
]
